### ISSUE TITLE
How to change code dynamically

### ISSUE THREAD

**Issue by windinsky** [gluons/vue-highlight.js#1]
Hello. since you are using slot to pass code to this plugin. If the code was changed outside. There seems no way to pass the new code to this plugin. Maybe you could consider using prop instead?

Great plugin btw!

**Comment by windinsky** [comment]
I forked a new version and changed the code. It works for now but my code is tricky. Since I'm new to vue, hopefully you could figure out a better way to solve this problem. 

Thanks.

**Comment by gluons** [comment]
I've implemented this feature in [`code-binding`](https://github.com/gluons/vue-highlight.js/tree/code-binding) branch. You can see it in [ad6ed3d](https://github.com/gluons/vue-highlight.js/tree/ad6ed3dbae4a68cc9c5738450561ccc631204771).

Thank you for `textContent` idea. It works nicely!.

**Comment by windinsky** [comment]
So sorry for the late response. My first baby is about to born and I'm quit busy these days😁. I'll try your new code and resp to you ASAP.

**Comment by windinsky** [comment]
I've tried your new code. the code binding works. sadly this version would cause an error while compiling on the server side(ssr), I have to delete the sub component part to make it work:

`<template lang="html">
	<pre v-if="hasCode && !inline"><code ref="code-elm" :class="lang">{{ code }}</code></pre>
	<pre v-else-if="!hasCode && !inline"><code ref="code-elm" :class="lang"><slot></slot></code></pre>

	<span v-else-if="hasCode && inline"><code ref="code-elm" :class="lang" :style="codeStyles">{{ code }}</code></span>
	<span v-else="!hasCode && inline"><code ref="code-elm" :class="lang" :style="codeStyles"><slot></slot></code></span>
</template>


<script>

import hljs from 'highlight.js';

export default {
	name: 'highlight-code',
    computed:{
		hasCode() {
			return (typeof this.code === 'string') && (this.code.length > 0);
		}
    },
	props: {
		lang: String,
		inline: {
			type: Boolean,
			default: false
		},
		code: String
	},
    methods: {
		init() {
			let codeElm = this.$refs['code-elm'];
			if (this.hasCode) {
				codeElm.textContent = this.code;
			}
			hljs.highlightBlock(codeElm);
		}
    },
	mounted() {
		this.init();
	},
	updated() {
		this.init();
	}
};
</script>`

**Comment by gluons** [comment]
What's error on SSR?

**Comment by windinsky** [comment]
"document" is not defined

**Comment by windinsky** [comment]
It seems like vue is trying to render a style tag for the sub component. the error is triggered from addStyle function

**Comment by windinsky** [comment]
`function addStyle (obj /* StyleObjectPart */) {
  var update, remove

// here
  var styleElement = document.querySelector('style[data-vue-ssr-id~="' + obj.id + '"]')

  if (styleElement) {
    if (isProduction) {
      // has SSR styles and in production mode.
      // simply do nothing.
      return noop
    } else {`

**Comment by gluons** [comment]
That error occurs because I forgot to remove [trailing](https://github.com/gluons/vue-highlight.js/blob/b3bdb3bc4143f014a304a9061ef193300c5fbcdc/src/components/block-code.vue#L42) [`style` tag](https://github.com/gluons/vue-highlight.js/blob/b3bdb3bc4143f014a304a9061ef193300c5fbcdc/src/components/inline-code.vue#L50) in sub components. 😅

I've fixed it in 6bff118f26e925e52e8ad42c2d1992b537a7686b. Please try and tell me. 🙃

**Comment by windinsky** [comment]
nicely done~~!! It worked.

however there is a little typo in webpack.prod.config.js

        output: {
                path: path.resolve(__dirname, '../dist'),
-               filename: 'vue-highlight.min.js',
+               filename: 'vue-highlight.js',
                libraryTarget: 'umd',
                library: 'VueHighlightJS',
                umdNamedDefine: true
        },

to match package.json

main:'dist/vue-highlight'

**Comment by gluons** [comment]
I decide to use **unminified** file as `main` file. Former `main` is **minified** file.

**Comment by gluons** [comment]
@windinsky [1.1.0](https://github.com/gluons/vue-highlight.js/releases/tag/v1.1.0) released. 🎉
