### ISSUE TITLE
Move highlight.js from peerDependencies into dependencies

### ISSUE THREAD

**Issue by ColinTree** [gluons/vue-highlight.js#10]
It seems more understandable to be in `dependencies` rather than in `peerDependencies` (in `package.json`)

Thanks

**Comment by gluons** [comment]
I don't want to fix `highlight.js` to specific version in `dependencies`.  
But maybe I'll change my decision about this. 😅

**Comment by gluons** [comment]
I've thought over your suggestion. I think I will keep `peerDependencies` as-is.

**Reasons:**
- `peerDependencies` will let you freely pick a version of `highlight.js` that you want.
- In OSS, some bugs will happen in some version of package that you use. If I add it into `dependencies`, it'll use the latest version that match `dependencies`. So, it'll be hard to rollback to working version.
- You may use [Yarn resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) to pick specific version. But why you have to do many step to solve a temporary bug. And it isn't possible for npm user to use **resolutions** feature now.

The easy step is specifying the version that you want in your own `package.json`. It's better. 😊

@ColinTree What do you think?

**Comment by ColinTree** [comment]
That sounds reasonable, but is there a lowest requirement in dependencies' versions? You can then add it into package.json.
And another solution is to simplily add an notice about installing dependencies in README.md XD

**Comment by gluons** [comment]
Lowest version is included in `peerDependencies` (`"highlight.js": "^9.11.0"`). The package manager will warn you if it mismatch.

I'll add installation command like this in README.
```bash
npm install highlight.js vue-highlight.js
```

**Comment by gluons** [comment]
I'll close this.  
Readme has been updated to single line command. It can be copied easily.
