### ISSUE TITLE
Built size

### ISSUE THREAD

**Issue by deulos** [gluons/vue-highlight.js#11]
Hello, and first of all thanks a lot for your component. This was the first I liked after trying other 3.

Everything works great although I am facing a problem with the built size and I am afraid it is caused by including all languages and themes.

I tried defining everything in main.js like explained in highlight.js but without success. Can you please tell me if there is a way to reduce the size?

You can check it by yourself at https://deulos.github.io/vue-daval/ and notice that chunk-vendors is about 1.2 MB of which 800KB comes from the vue-highlight.js

You can also find my code and repo at https://github.com/deulos/vue-daval

Clonning it and running npm run build-docs will let you know the info.

Thanks!

**Comment by gluons** [comment]
I've create #12 to solve this issue. I use [dynamic import](https://github.com/tc39/proposal-dynamic-import) to split **Highlight.js** languages into chunks.

You can try it by yourself. It's currently on [`version-3`](https://github.com/gluons/vue-highlight.js/tree/version-3) branch.  

```bash
git clone https://github.com/gluons/vue-highlight.js.git -b version-3
cd vue-highlight.js
yarn
yarn build
cd <your repo>
yarn add file:<path to vue-highlight.js> # install vue-highlight.js locally
```

Your site will load only languages that you want.

**Before:**

Transfered: 1.20 MB / 373.26 KB

![before](https://user-images.githubusercontent.com/4688092/50507835-bbeef680-0ab1-11e9-90df-14d83e23926a.png)

**After:**

Transfered: 627.32 KB / 166.39 KB

![after](https://user-images.githubusercontent.com/4688092/50507847-c14c4100-0ab1-11e9-985f-f025415cde6e.png)

> Sorry for my browser language. I use Firefox with Thai language. 😅

**Comment by deulos** [comment]
Terrific!

I will update it tomorrow morning and let you know.

Thanks a lot mate!

**Comment by deulos** [comment]
Hey! just tested it and seems to work as expected although when I build docs now (npm run build-docs), it is creating 374 files in vue-daval/docs/js and is not really nice...

What about if we do the following and you just forget about the languages?
``` javascript
import hljs from 'highlight.js/lib/highlight';
import javascript from 'highlight.js/lib/languages/javascript';
import 'highlight.js/styles/ir-black.css';
hljs.registerLanguage('javascript', javascript);
```

This way everybody just import what they need and you save headaches

**Comment by gluons** [comment]
I want to keep Vue Highlight.js simple as much as possible. But seem we face some limitation.

There's a trade-off between simplicity and performance. 😅

Thank you for your suggestion. I'll try the best.

**Comment by gluons** [comment]
New version now lives on npm with `beta` tag. [Grab it and try it](https://www.npmjs.com/package/vue-highlight.js/v/beta) 😄

**Comment by deulos** [comment]
Awesome man, works like a charm and now it loads 200% faster.

Before:
![image](https://user-images.githubusercontent.com/6222619/50571026-7a0acc80-0d9f-11e9-8977-5e4059b526f3.png)

After:
![image](https://user-images.githubusercontent.com/6222619/50571035-960e6e00-0d9f-11e9-852d-1aef65261577.png)

Good job!!!

**Comment by gluons** [comment]
Version 3 has been published. 🙂
