### ISSUE TITLE
Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

### ISSUE THREAD

**Issue by TuguldurJ** [gluons/vue-highlight.js#15]
When installing this package via NPM, I get the following warnings and errors:
`npm install highlight.js vue-highlight.js`
> npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated hoek@0.9.1: The major version is no longer supported. Please update to 4.x or newer
npm ERR! path /Users/******/node_modules/highlight.js/tools/build.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/******/node_modules/highlight.js/tools/build.js'
npm ERR! enoent This is related to npm not being able to find a file.

Please consider that [highlightjs](https://github.com/highlightjs/highlight.js/releases) updated their package.

**Comment by gluons** [comment]
`vue-highlight.js` does not contain any `minimatch` in dependencies.  
See http://npm.broofa.com/?q=vue-highlight.js

Currently, `vue-highlight.js` does not contain any vulnerability.
See [![Snyk Vulnerabilities for npm package](https://img.shields.io/snyk/vulnerabilities/npm/vue-highlight.js.svg?style=flat-square)](https://snyk.io/test/npm/vue-highlight.js)

`highlight.js` install error may relate to highlightjs/highlight.js#1984
