### ISSUE TITLE
How do I use these tags for the script template span?

### ISSUE THREAD

**Issue by NewPrototype** [gluons/vue-highlight.js#7]
How do I use these tags for the script template span?

**Comment by gluons** [comment]
Could you give me more information? I don't understand.

**Comment by NewPrototype** [comment]
span,script,html tags

**Comment by gluons** [comment]
Did you mean using with HTML code? If you mean that, you should escape HTML tags before add into slot.

See isagalaev/highlight.js#866

**Example:**

https://github.com/gluons/vue-highlight.js/blob/0d8cb9ac0c52db3d8ed72a2a0f0f21c9b861f9c1/dev/App.vue#L14-L35

**Comment by NewPrototype** [comment]
If it's not convenient to do more, I find the latest method, es6 string parsing can be resolved, but the script tag cannot use this method

**Comment by gluons** [comment]
If place HTML tag directly, it will be interpreted as HTML element by browser.
It is constraint. **Highlight.js** cannot resolve it.

Maybe [escape-goat](https://github.com/sindresorhus/escape-goat) can help you?

**Comment by NewPrototype** [comment]
This problem has been resolved and es6 string parsing can be achieved

**Comment by gluons** [comment]
Great. Hope you enjoy using `vue-highlight.js`. 😉

**Comment by NewPrototype** [comment]
Will the

**Comment by gluons** [comment]
> the script tag cannot use this method

Did you mean this issue? [“Unterminated template literal” syntax error when literal contains script tag](https://stackoverflow.com/questions/36607932/unterminated-template-literal-syntax-error-when-literal-contains-script-tag)
