### ISSUE TITLE
Tab long space

### ISSUE THREAD

**Issue by adrianoresende** [gluons/vue-highlight.js#8]
![image](https://user-images.githubusercontent.com/798755/30673191-b70884ce-9e47-11e7-8acf-5a9c117d1048.png)

**Comment by gluons** [comment]
It's tab character (`	`). Maybe I need `tab-size`](https://developer.mozilla.org/en-US/docs/Web/CSS/tab-size) CSS.

**Comment by gluons** [comment]
Fixed by [`tab-size`](https://developer.mozilla.org/en-US/docs/Web/CSS/tab-size).
